### ISSUE TITLE
Remove div containing button slot content

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/vue-vocabulary#106]
Remove [this div](https://github.com/creativecommons/vue-vocabulary/blob/master/src/elements/Button/Button.vue#L20) inside the `<button>` element which contains the `<slot>` content. This makes it difficult for users of Vocabulary to set their own content styles if they choose to.

**Comment by theprover97** [comment]
Hey @brenoferreira , can i work on this issue?

**Comment by dhruvkb** [comment]
One by one @theprover97.

**Comment by jshreyans** [comment]
Are there any changes required with #113? @dhruvkb

**Comment by dhruvkb** [comment]
I haven’t been able to find time to review. Feel free to work on other issues in the meantime.

**Comment by dhruvkb** [comment]
This is superseded by #115.
