### ISSUE TITLE
Switch to declarative Storybook syntax

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#108]
The Storybook that has been set up in the project uses the old Storybook configuration syntax consisting of `config.js` and `addons.js`. With the new release, Storybook is moving towards a new syntax with the old one to be deprecated and eventually discontinued.

The goal is to implement the [new syntax](https://medium.com/storybookjs/declarative-storybook-configuration-49912f77b78) so that there are no issues in the future.

**Comment by Dhruvi16** [comment]
I would like to take this up!
Thank you.

**Comment by dhruvkb** [comment]
@Dhruvi16 go ahead. Refer to Vocabulary for a working implementation.
