### ISSUE TITLE
Integrate JavaScript Standard Style with ESLint

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#109]
**Description**
The project follows [JavaScript Standard Style](https://standardjs.com) but doesn't configure it in ESLint. This causes new developers to either manually configure Standard or end up following their linter and submit problematic changes involving spaces, semicolons and the like.

**Reproduction**
Set up the repository in a fresh editor or IDE. Run code format. A number of code styling decisions that are aligned with Stardard will either show up as errors/warnings or worse, be _corrected_.

**Expected behavior**
The code, which complies with Standard should not change at all. The default ESLint setup should automatically inherit rules from Standard.

**Comment by jshreyans** [comment]
I'd like to take this up. 
But before I start, if I understand correctly, I just need to add the `standard` field to the `extends` array in [.eslint.rc](https://github.com/creativecommons/vue-vocabulary/blob/master/.eslintrc.js)?

**Comment by dhruvkb** [comment]
The `extends` array already contains `@vue/standard` and yet the error persists for @chidexebere. I think he should weigh in on this issue.

**Comment by jshreyans** [comment]
@chidexebere how do you propose I move forward with this?

**Comment by chidexebere** [comment]
@jshreyans can you try reproducing the issue and to see if eslint throws errors and warning? 
Like @dhruvkb said, the `extends` array already contains `@vue/standard `  but I was still getting errors with eslint. 

I recently upgraded **node** on my system to **version 12.14.1** and am currently not getting those errors. Also I did not run any update on my editor (VS code).

If this error can not be reproduced, I think this issue should be closed

**Comment by jshreyans** [comment]
The issue persists for me. I ran these 2 code formatters:
- [Prettier](https://prettier.io/)
- [Vetur](https://github.com/vuejs/vetur)

Both of them made _significant_ code format changes.

**Comment by dhruvkb** [comment]
Prettier is an opinionated formatter. Since Standard as Prettier follow different rules, they will most certainly clash and override each other. Vetur is tooling, so it internally uses some other tool for the actual lint process, which might have similar clashes. The goal is to check if ESLint in particular, without a formatter like Prettier, will raise errors when run on the codebase.

**Comment by jshreyans** [comment]
So I finally ran ESLint on the code _after_ disabling any other formatters/tooling or otherwise and also upgraded my node setup to v12 as @chidexebere suggested. 

The errors don't show up after this. I guess it was a problem with the node setup for both of us and the `@vue/standard` setting works fine after all. I think this issue can be closed now.

**Comment by dhruvkb** [comment]
Great, that’s good to know!
