### ISSUE TITLE
Update Docker Compose configuration file

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#110]
The [Docker Compose file](https://github.com/creativecommons/vue-vocabulary/blob/master/Dockerfile) for the project, written in the initial days of the project has now gone out of sync with the capabilities and features of the project. The goal is to update the file in accordance with the current state and eventually push for it to the the standard development environment for the project.

**Comment by jshreyans** [comment]
Working on this

One thing I'd like to point out:
https://github.com/creativecommons/vue-vocabulary/blob/4a4819ad75962e418c4f086927f860197d53329a/Dockerfile#L2
Using the latest version of Node might lead to problems in the sense that the latest release from Node might not support some of the features of this project. Wouldn't it be better to use a stable release like v10 or v12?

**Comment by dhruvkb** [comment]
@jshreyans I guess you're right, LTS would be better.

```Dockerfile
FROM node:lts
```

**Comment by jshreyans** [comment]
@dhruvkb would we want the user to have the Vue CLI installed globally on the machine via the Dockerfile? The version that I'm working on has the line:
```
RUN npm install -g @vue.cli
```
I just wanted to confirm if this is required or not

**Comment by jshreyans** [comment]
Also, does the project depend on the Dockerfile to serve Vocabulary? Because the [docker-compose.yml](https://github.com/creativecommons/vue-vocabulary/blob/master/docker-compose.yml) file already contains the serve command.

**Comment by dhruvkb** [comment]
@jshreyans the commands written in the Dockerfile are run inside the container. So when we write
```Dockerfile
RUN npm install -g @vue/cli
```
the package `@vue/cli` is installed inside the container, not globally on the machine.

The files `Dockerfile` and `docker-compose.yml` go hand in hand. `Dockerfile` is used to build the images and `docker-compose.yml` is used to create and manage containers that use this image.

**Comment by jshreyans** [comment]
@dhruvkb Thanks for the clarifications. I'll be sending a PR shortly.
This was my first encounter with Docker and I'm looking forward to your reviews!

**Comment by dhruvkb** [comment]
The PR is pretty solid for your first encounter. Good work!
