### ISSUE TITLE
Sync Button Styles from Vocabulary to Vue Vocabulary

### ISSUE THREAD

**Issue by annatuma** [creativecommons/vue-vocabulary#115]
**Description**
We need to:
1. Remove all existing Button styles from Vue Vocabulary:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/elements-button--branded
2. Sync Button styles from Vocabulary to Vue Vocabulary, so that all buttons in Vue Vocabulary look like this:
https://cc-vocabulary.netlify.com/storybook/?path=/story/elements-button--button

I.e. Vue Vocabulary should match Vocabulary completely for Button styles.

**Comment by kgodey** [comment]
We're removing buttons from Vue Vocabulary.
