### ISSUE TITLE
Remove Emoji element from Vue Vocabulary

### ISSUE THREAD

**Issue by annatuma** [creativecommons/vue-vocabulary#116]
**Description**
We want to remove the Emoji Elements (both styles - Outputs and With Text) from Vue Vocabulary, as there is no use case at present:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/elements-emoji--with-text

**Comment by dhruvkb** [comment]
@annatuma it's actually required to make the emoji rendering consistent across browsers and platforms (#9). While not being used in the present in any app, I think it would be hard to argue that no pages of no apps by CC will render emoji in the future.

**Comment by annatuma** [comment]
That's good background @dhruvkb.

Knowing this, @hugosolar @brenoferreira @kgodey do you see any issue with keeping Emoji in Vue Vocabulary? If we keep it there, we need to add it to Vocabulary as well.

**Comment by kgodey** [comment]
We mean adding it to the Storybook. I'm fine with keeping it in.
