### ISSUE TITLE
Changes to Vue Vocabulary ChoiceField

### ISSUE THREAD

**Issue by annatuma** [creativecommons/vue-vocabulary#117]
Blocked by: https://github.com/creativecommons/vocabulary/issues/61
Do not commence work until 61 is complete.

**Description**
We want to make updates to the ChoiceField component in Vue Vocabulary:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/elements-choicefield--branded

1. Remove all existing styles, except Unstyleable
2. Change the name of Unstyleable to be "Checkbox"
3. Change the name of Choicefield to be "Form"
4. Add Text Input styles to newly-named "Form" element, to match Figma DL:
-- We should include knobs to indicate height (40px vs 62px) and state (checkbox that makes the text input disabled, default state is enabled).
5. Identify the SelectField style currently used in the Vocabulary footer (https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/patterns-footer--customised), move that specific style up to the "Form" element, and re-style it to match the Select design in Figma. This ensures that the Vocabulary footer will not break. 
6. Edit re-named Checkbox style to ensure it matches Figma DL, perhaps with use of knobs (i.e. checked, unchecked, unavailable).

Figma DL:
https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A250

**Comment by panchovm** [comment]
The form page has been updated with the above changes.

**Comment by dhruvkb** [comment]
ChoiceField is now just a standard checkbox and correspondingly will not have a component in Vocabulary or Vue Vocabulary.

**Comment by kgodey** [comment]
Yes, we can.
