### ISSUE TITLE
Updates to GitHub Corners

### ISSUE THREAD

**Issue by annatuma** [creativecommons/vue-vocabulary#118]
**Description**

We want to:
1. Remove the Branded and Colored options.
2. Update Invertible to have two knobs: Black on white, or White on black.
3. Keep Corners (they can be left or right).
4. Remove Positions.

Related ticket: https://github.com/creativecommons/vocabulary/issues/52

**Comment by dhruvkb** [comment]
@annatuma if this is not urgent, can we let volunteers attempt it? It seems like a fairly simple issue to fix while gaining some exposure.

**Comment by kgodey** [comment]
@dhruvkb yes that's fine

**Comment by chidexebere** [comment]
Will take this

**Comment by chidexebere** [comment]
On a second thought, this can go to volunteers from GSOC, since its relatively easy and a good first issue. I will pick up another.

**Comment by jshreyans** [comment]
Can I take this up?

**Comment by kgodey** [comment]
I'll leave assigning this issue to @dhruvkb

**Comment by AmanR28** [comment]
Can I work on this?

**Comment by Blackcipher101** [comment]
If no one is working on it can I work on it

**Comment by dhruvkb** [comment]
@AmanR28 and @Blackcipher101  apologies for not being able to assign it to you, please feel free to pick one of the many other issues and message me on Slack if I take too long.

**Comment by jshreyans** [comment]
> Update Invertible to have two knobs: Black on white, or White on black.

I've sent a PR for this (#155) but I'm not too sure if my implementation of this feature is correct. Looking forward to reviews!
