### ISSUE TITLE
Changes to ImageView Element

### ISSUE THREAD

**Issue by annatuma** [creativecommons/vue-vocabulary#121]
**Description**
We want to remove the Scaled style from the ImageView Elements. We have no present use case, and if we did have a need there are other ways to solve this (e.g. through containers). 

We will continue to make use of Circleable and Hoverable. These should be updated to match the Figma DL:
https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=576%3A0

We also want to rename the element "Image" instead of "ImageView".

**Comment by dhruvkb** [comment]
@annatuma I think we cannot name the element `Image` as it is one of HTML reserved tags.

**Comment by kgodey** [comment]
@dhruvkb could we name the Vocabulary class Image and the Vue Vocabulary component `ImageView`?

**Comment by dhruvkb** [comment]
@kgodey having common names for the classes and the elements would be ideal.

**Comment by kgodey** [comment]
Okay, we can stick with `ImageView`

**Comment by dhruvkb** [comment]
This is blocked till the corresponding component exists in Vocabulary.
