### ISSUE TITLE
Updates to LicenseIconography

### ISSUE THREAD

**Issue by annatuma** [creativecommons/vue-vocabulary#123]
**Description**
We want to make some changes to the LicenseIconography element:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/elements-licenseiconography--creative-commons

1. Break each icon into individual Styles, to match the Downloads page:
https://creativecommons.org/about/downloads

2. Remove "Popupable" style.

**Comment by dhruvkb** [comment]
@annatuma I would request some more clarification for point 1 which is to break each icon down. Each icon is, as of now, already an individual. They are just shown together in the stories. 

As for point 2, the popups were added to address #21. Does the redesigned license chooser not need these popups anymore?

**Comment by kgodey** [comment]
@dhruvkb We wanted each icon to have a separate story for clarity.

**Comment by dhruvkb** [comment]
Okay, that then is a fairly simple change.

**Comment by Dhruvi16** [comment]
I would like to take this up.
Thank you.
Dhruvi

**Comment by dhruvkb** [comment]
@Dhruvi16 please go ahead.
