### ISSUE TITLE
Remove Vocabulary Styleguide

### ISSUE THREAD

**Issue by annatuma** [creativecommons/vue-vocabulary#124]
**Description**
The Vocabulary Styleguide is still online:
https://cc-vue-vocabulary.netlify.com/styleguide/

Let's remove this. If we can set a redirect on the URL, let's send it to the Storybook instead. It's confusing to have the Styleguide still live.

**Comment by dhruvkb** [comment]
Seeing as @panchovm has been crafting detailed rules for design usage in Figma, the styleguide has been rendered redundant. I'll take my words back and re-activate the issue.

**Comment by dhruvkb** [comment]
This has been fixed in 37ebcf1c.
