### ISSUE TITLE
Remove Tabbed (from Layouts) and Associated Styles

### ISSUE THREAD

**Issue by annatuma** [creativecommons/vue-vocabulary#133]
**Description**
We'd like to remove Tabbed (from Layouts) and all associate styles:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/layouts-tabbed--branded

Note that we are maintaining TabbedPane (in use by Extension), and will be making design updates to it, to reflect use cases in License Chooser and CC Search.

**Comment by chidexebere** [comment]
The TabbedPane is part of the Tabbed component. Removing the Tabbed component also means removing the TabbedPane. Should I still go ahead and remove the Tabbed (which will include TabbedPane?

**Comment by kgodey** [comment]
We want to keep one of the Tabbed components since it's used in the browser extension. I'll defer to @dhruvkb on how best to refactor so that we only have one of the components.

**Comment by dhruvkb** [comment]
@annatuma and @kgodey, as @chidexebere said the `Tabbed` component contains one or more `TabbedPane` components. The tabbed panes contain the content and the parent determines which to activate and designates that one with the appropriate class. They are two parts of a whole.

**Comment by dhruvkb** [comment]
The only refactoring I can see is if we enclose the pane within the `Tabbed` component as [`Tabbed.Pane`](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Tab/Tab.js#L79) the way Semantic UI handles it.

**Comment by kgodey** [comment]
@dhruvkb Could we just have a single `TabbedPane` component that has everything in both Tabbed and TabbedPane? We don't need multiple variants of it.

**Comment by dhruvkb** [comment]
This issue has been superseded by #197.
