### ISSUE TITLE
Remove TableCell (Layouts) and style

### ISSUE THREAD

**Issue by annatuma** [creativecommons/vue-vocabulary#134]
**Description**
We want to remove TableCell from Layouts in Vocabulary, as well as its one associated style (Indicating): https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/layouts-tablecell--indicating

**Comment by chidexebere** [comment]
TableCell makes up the Table component. Removing TableCell will also mean removing the Table component.  Should I go ahead and remove the TableCell and Table component?

**Comment by dhruvkb** [comment]
@annatuma, @chidexebere is right here, the `Table` is contains `TableCell`s much like in #133. A similar solution could be considered here if that's okay?

**Comment by kgodey** [comment]
@dhruvkb I'm not sure what "a similar solution" means, please describe in detail what the resulting component would look like.

**Comment by dhruvkb** [comment]
Superseded by #170.
