### ISSUE TITLE
Create the Logo component

### ISSUE THREAD

**Issue by annatuma** [creativecommons/vue-vocabulary#135]
**Description**
We want to change the name of the BrandImagery (in Patterns) to be "Logos". We want to move it from Patterns to Elements.

**Comment by dhruvkb** [comment]
@annatuma is this just a name/classification change or will we be redoing the component entirely from the ground up based on the discussion in Asana?

**Comment by kgodey** [comment]
@dhruvkb this is just a name change.

**Comment by Bob160** [comment]
@dhruvkb and @kgodey can I please handle this issue?

Thanks

**Comment by dhruvkb** [comment]
@Bob160 sure, go ahead.

**Comment by Bob160** [comment]
@dhruvkb , I intend to:
1.  Change BrandImagery folder to Logo,  same with the two files inside... The. vue file and. stories.js file;
2. Then, inside the files change all instances of BrandImagery to Logo;
3. Then move the folder to elements; and lastly,
4. Change all instances of patterns to elements.

Is this the way to go? What do you think?

**Comment by Bob160** [comment]
@dhruvkb and @annatuma @kgodey @hugosolar 

 I intend to:
1.  Change BrandImagery folder to Logo,  same with the two files inside... The. vue file and. stories.js file;
2. Then, inside the files change all instances of BrandImagery to Logo;
3. Then move the folder to elements; and lastly,
4. Change all instances of patterns to elements.

Is this the way to go? What do you think?

**Comment by dhruvkb** [comment]
The increased scope of the issue is to create the `Logo` component that takes the file name and directly renders the logo using the SVG assets from the `@creativecommons/vocabulary` package that is installed as a dependency of `@creativecommons/vue-vocabulary`.

**Comment by dhruvkb** [comment]
With some new developments, we've decided to skip building the Logos component entirely opting to directly use [the SVG assets of the logos from Vocabulary](https://cc-vocabulary.netlify.com/?path=/story/assets-logos--cc-logomark).
