### ISSUE TITLE
Update Definition (Patterns)

### ISSUE THREAD

**Issue by annatuma** [creativecommons/vue-vocabulary#136]
**Description**
We want to make changes to the Definition (in Patterns).

1. Remove Colored and Indicating.
2. Rename Branded to be "Default"
3. Rework "Default" to only match the style necessary for the Vocabulary homepage.

We will eventually switch to a logo that matches the rest of CC products.

**Comment by dhruvkb** [comment]
With the Vocabulary homepage being in Storybook, this component is no longer necessary.
