### ISSUE TITLE
Increase DRY-ness in documentation code examples

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#14]
Many examples of code in the documentation, notably for the colours and shades, resort to manually writing examples for every colour and shade. This is a very terrible approach, one that will inevitably lead to hassles when updates are required.

A simpl improvement to this approach would be to use arrays, dictionaries and `v-for` to programatically generate `GridCell`s. An alternative more intensive approach would be the playground experience suggested in #6.

This `v-for` methodology has been used to update documentation for the `Grid` component, which can be used as reference if needed.

**Comment by dhruvkb** [comment]
Reopening as it was a partial fix.

**Comment by deboragaleano** [comment]
Hi, I'm an Outreachy applicant. I see that this issue is still open. Could I try to work on it as a first issue? Thank you!

**Comment by dhruvkb** [comment]
Sure, submit separate PRs for every component whose documentation you make DRY-er. See #33 and #34 for reference.

**Comment by deboragaleano** [comment]
So sorry but I won't be able to work on this issue in the end, I should leave it to another applicant. Thank you!

**Comment by Eniola4031** [comment]
Hello, I am interested in working on the issue.

**Comment by dhruvkb** [comment]
@Eniola4031, you're welcome to take this up!

**Comment by Eniola4031** [comment]
@dhrvkb How do i reach you please, i need some clarifications?

**Comment by dhruvkb** [comment]
Slack would be the best way to reach me.

**Comment by dhruvkb** [comment]
This issue is being closed in light of the shift from Styleguidist to Storybooks.
