### ISSUE TITLE
Write More Test

### ISSUE THREAD

**Issue by AmanR28** [creativecommons/vue-vocabulary#142]
**Description**

Currently, there are tests only for Heading and Paragraph in the Elements section and for token sections.

**Problems solved**

It might happen that the new code may break something.

**Additional context**

1 test suite per PR

**Want to take up?**

[Yes|

**Comment by AmanR28** [comment]
Can I write tests for button section in elements?

**Comment by dhruvkb** [comment]
This is a duplicate of #4. Closing.
