### ISSUE TITLE
Update Locale to match Figma Design Library

### ISSUE THREAD

**Issue by panchovm** [creativecommons/vue-vocabulary#149]
We need to update the Locale element based on the Design Library file

**Comment by dhruvkb** [comment]
Depends on the redesign on the `SelectField` component.

**Comment by kgodey** [comment]
@dhruvkb what exactly do you need here to be unblocked and from whom?

**Comment by dhruvkb** [comment]
1. The `SelectField` component design needs to be updated in Vocabulary first (could be done by anyone). 
2. A new Vocabulary build needs to be published by @brenoferreira.
3. The dependency needs to be updated in Vue Vocabulary by me.
4. The `SelectField` component needs to be updated with the new design by anyone.
5. This issue can be worked on and resolved.

**Comment by kgodey** [comment]
@dhruvkb could you make tickets for those steps or link to the appropriate tickets?
