### ISSUE TITLE
Navigation should support multiple levels

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#16]
Currently the component `Navigation` and it's children `NavigationLink`s only support single level navigation. This is quite restrictive because a number of sites, particulary those of Creative Commons, do have multi-level navigation.

The goal is to make it so that `NavigationLink`s be capable of being nested, leading to a navigation tree structure instead of a list.

**Comment by rashadmad** [comment]
I was a bit confused by this issue-https://github.com/creativecommons/cc-vocabulary/issues/13 and wanted the opportunity to complete another issue first(that is easier) Can I be put down for this issue?

**Comment by dhruvkb** [comment]
Okay, go ahead with this. Do submit your designs as an idea first so that we may lock down on usability before implementing it in code.

**Comment by Dhruvi16** [comment]
I would love to take this up!
Thank you.
Dhruvi

**Comment by dhruvkb** [comment]
@Dhruvi16 you’re assigned to an issue already so let’s go through the issues one by one.

**Comment by kgodey** [comment]
Closing this because we don't have a Navigation component in the new Figma Design Library. We'll reopen if needed.
