### ISSUE TITLE
the css color property is wrongly used.

### ISSUE THREAD

**Issue by aashimgarg** [creativecommons/vue-vocabulary#160]
The CSS property for the heading is wrongly used that why it not showing the heading in the orange color at various places.

Relevant screenshot :-
![Screenshot from 2020-02-09 19-24-36](https://user-images.githubusercontent.com/55639487/74103796-28716b80-4b75-11ea-9f2a-a2d1afd30be4.png)

**Comment by dhruvkb** [comment]
We're deleting the Styleguide eventually so fixing minor bugs in the Styleguide (which there will be a lot of, given that it hasn't been updated in a long time) is not on our roadmap.
