### ISSUE TITLE
Add the Progress layout

### ISSUE THREAD

**Issue by panchovm** [creativecommons/vue-vocabulary#165]
Add the Progress layout and its components: the white boxes to indicate the different states. The section is in Design Library.

**Comment by mercyikpe** [comment]
I'll like to implement this.

**Comment by dhruvkb** [comment]
@mercyikpe start with creativecommons/vocabulary#112.

**Comment by mercyikpe** [comment]
Alright, Thank you.

**Comment by dhruvkb** [comment]
We're not really sure if we'll implement this in Vue Vocabulary.
