### ISSUE TITLE
Update usage and contribution guidelines

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#167]
Once Vocabulary has been redeveloped, the usage and contribution guidelines will be out of date and will need major rewritings to be in sync with the new codebase. The goal is to update these guidelines and instruction documents.

**Comment by dhruvkb** [comment]
References creativecommons/vocabulary#120.

**Comment by miracle-E** [comment]
I'm an outreachy applicant and would love to work on this.

**Comment by dhruvkb** [comment]
@miracle-E I'm not sure if you'd be interested after all this while but there's no harm in asking. For reference,  see creativecommons/vocabulary#214 and creativecommons/vocabulary#272.

**Comment by dhruvkb** [comment]
Resolved by #200.
