### ISSUE TITLE
Navigation looks ugly when more links than width

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#17]
The `Navigation` components looks quite terrible when the number of `NavigationLink` children are more than the screen can handle. This can be seen by increasing the number of links in the navigation to a large number and is particularly easy to spot on tablets in portrait orientation.

Designing a better navigation bar is a pressing concern, in light of #16. 

![image](https://user-images.githubusercontent.com/16580576/63910430-483c2980-ca44-11e9-8b5d-179762aee448.png)

**Comment by mouracamila** [comment]
I'd like to work on that issue

**Comment by dhruvkb** [comment]
Sure go ahead!

**Comment by dhruvkb** [comment]
@mouracamila Since this is a `discussion: rfc` issue, it would be preferable that you present your idea about a potential fix first and get it ratified before coding right away.

**Comment by mouracamila** [comment]
@dhruvkb, I suggest, could are created the "menu hamburguer":
- When there are more than 2 items in navigationLink
- When the resolution is less than 700px (approximate resolution with iPad).
What do you think?

**Comment by mouracamila** [comment]
@dhruvkb I think it would be interesting to create another header model. It could have the "menu collapse", for more "NavigationLink". In which would be a user choice which heading would best suit their needs. What do you think?

**Comment by dhruvkb** [comment]
@mouracamila the `Header` component is not related to this issue. The component `Header` contains a `slot` that can be populated by any component or DOM, which is generally the `Navigation` component. The styling for the `Navigation` component needs to be updated to accommodate a large number of `NavigationLink` components.

**Comment by dhruvkb** [comment]
> @dhruvkb, I suggest, could are created the "menu hamburger":
> 
>     * When the resolution is less than 700px (approximate resolution with iPad).
>       What do you think?

Most popularly the hamburger menu is a staple of mobile screens. I haven't come across many sites that use the hamburger on tablet-sized resolutions. Are there any references that I could see for hamburger-menus on tablets?

**Comment by mouracamila** [comment]
@dhruvkb One solution that I found interesting was deleted the icons and the border-right. 
![Screenshot from 2019-10-14 10-55-47](https://user-images.githubusercontent.com/41678283/66739738-9fba1b80-ee71-11e9-960b-1f769d5c7733.png)

**Comment by mouracamila** [comment]
![Screenshot from 2019-10-14 11-01-16](https://user-images.githubusercontent.com/41678283/66739943-3090f700-ee72-11e9-94c7-adbca995bd09.png)
About the menu hamburger, Bootstrap4 has the navbar-collapse that creates the collapse menu with a default resolution of less than 991px. Websites have this feature https://angular.io/docs and https://vuejs.org/.

**Comment by dhruvkb** [comment]
Okay @mouracamila let's use the hamburger menu on tablets (portrait orientation) and mobile. I think horizontal scrolling would be acceptable in the navigation if the width exceeds the container size.

**Comment by dhruvkb** [comment]
@mouracamila any updates on this?

**Comment by SomtochiAma** [comment]
Hello @dhruvkb, can I get started on this issue and I wanted to ask if there is an already existing hamburger icon?

**Comment by dhruvkb** [comment]
@SomtochiAma please go ahead. We use [Font Awesome](https://fontawesome.com/) in our projects so you can use their [ham](https://fontawesome.com/icons/bars?style=solid)[burger](https://fontawesome.com/icons/hamburger?style=solid)[ icon](https://fontawesome.com/icons/bars?style=solid).

**Comment by SomtochiAma** [comment]
For clarification, am I also going to remove the icon and left-border plus the hamburder for the tablet and mobile

**Comment by dhruvkb** [comment]
@panchovm, please weigh in on this with the new header designs.

**Comment by kgodey** [comment]
@dhruvkb are you asking for new designs or for comments on an existing design?

**Comment by dhruvkb** [comment]
I'm asking him to send a picture of the new header designs (on various screens) so that we can get it implemented along with this change. It is a pretty drastic change as it is so if we had the new designs, we could potentially avoid another huge change a few weeks down the line.

**Comment by panchovm** [comment]
@dhruvkb As far as I know, a future project will redesign the header to be implemented across all the CC's websites. Therefore, it might change depending on that final definition. I will share with you the Zeplin project, where you will see the header on different pages.
