### ISSUE TITLE
Create the Table component

### ISSUE THREAD

**Issue by panchovm** [creativecommons/vue-vocabulary#170]
**Description**
With the `Table` component having been built in Vocabulary with the markup and styling already defined, it's time to get the Vue version of the component.

The Table component is a layout and as such has a lot of markup involved for even the very simple usecases. Having a Vue component with `slot`s takes a huge load off the developer to focus on the main content.

References:
- creativecommons/vocabulary#143
- [Table @ Figma](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=904%3A0)

**Comment by Dhruvi16** [comment]
I know it is assigned already. But still wanted to ask if I can help with this?
Thank you
Dhruvi.

**Comment by kgodey** [comment]
I'll leave assignment up to @dhruvkb and @hugosolar.

**Comment by dhruvkb** [comment]
Since Vue Vocabulary is not being actively worked on and @Dhruvi16 has considerable experience with `creativecommons/vocabulary`, I think it would be okay to let her try this.
