### ISSUE TITLE
Update the style of Tab component

### ISSUE THREAD

**Issue by panchovm** [creativecommons/vue-vocabulary#171]
Update the style of Tab component based on the element available on [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=933%3A0&viewport=25%2C233%2C0.47611111402511597).

**Comment by mercyikpe** [comment]
Hello, am interested in working on this.

**Comment by dhruvkb** [comment]
This is blocked at the moment by creativecommons/vocabulary#127.

**Comment by dhruvkb** [comment]
@mercyikpe this is available now? Still interested to work on it?

**Comment by megha070** [comment]
@dhruvkb I would like to take this up.

**Comment by Tanuj22** [comment]
@dhruvkb Can I work on this?

**Comment by dhruvkb** [comment]
Superseded by #197.
