### ISSUE TITLE
Update documentation according to updated Docker support

### ISSUE THREAD

**Issue by jshreyans** [creativecommons/vue-vocabulary#172]
**Description**
The Docker configuration has recently been updated after #119. The new configuration is in accordance with the scale of the application and supports building the website as well as the storybook. However, the [INSTRUCTIONS.md](https://github.com/creativecommons/vue-vocabulary/blob/master/INSTRUCTIONS.md) file could have more details about the build process and the ports to use to access the 2 services.

**Problems solved**
First time contributors will find it easier to build a dockerised version of the project and test out the various features.

**Alternatives**
None

**Additional context**

**Want to take up?**
Yes

**Comment by dhruvkb** [comment]
@jshreyans upon further inspection, the `INSTRUCTIONS.md` contains the [instructions for setting up the project with Docker](https://github.com/creativecommons/vue-vocabulary/blob/master/INSTRUCTIONS.md#dockerised-setup-recommended).

**Comment by jshreyans** [comment]
Yes, this setup does seem fine. I just thought we could make it more detailed but that might make it difficult for first-time contributors. We can close this issue then?
