### ISSUE TITLE
Delete Markdown files from the repo

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#176]
Since the styleguide has been deleted, the repository contains a lot of redundant `.md` files. Being incorrect, outdated and misleading, they must be deleted.

**Comment by jshreyans** [comment]
I'd like to take this up

**Comment by dhruvkb** [comment]
@jshreyans go ahead, this shouldn't take long.

**Comment by techievivek** [comment]
@dhruvkb If this is taking time, I would like to give it a try.
Thank you

**Comment by dhruvkb** [comment]
@techievivek we generally have a one week of inactivity rule before the issue is unassigned. It would be a good idea to find another issue in the meantime.

**Comment by techievivek** [comment]
@dhruvkb Ok sure. Thank you.

**Comment by jshreyans** [comment]
@dhruvkb Sorry for the delay. Will send a PR today. Just to clarify, by the redundant md files, we mean the files that accompany each component in their respective folders right?
