### ISSUE TITLE
giving link title in footer for better accessibility.

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/vue-vocabulary#190]
## Problem Description
we can add link title in footer for better accessibility,as it will help the user to know the given links in more clear way.

## Solution Description
we can add the title tag for the links.

## Additional context
i would like to take this up.

**Comment by dhruvkb** [comment]
@coderbabu10 there's actually a redesign of footer (creativecommons/vocabulary#92) in progress in `creativecommons/vocabulary`. I'm not sure your issue will still be relevant after that is done.

**Comment by coderbabu10** [comment]
Sir,I think having it will allow the user to know it in more descriptive way as it will come under the betterment of accessibility.

**Comment by dhruvkb** [comment]
@coderbabu10 I get the importance of adding the `title` attributes. I'm just concerned that after the redesign which is just around the corner, the code will change and any effort put into this will go wasted.

**Comment by dhruvkb** [comment]
This will be taken care of in the implementation of #196.
