### ISSUE TITLE
Create the Header component

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#193]
**Description**
With the `Header` component having been built in Vocabulary with the markup and styling already defined, it's time to get the Vue version of the component.

The Header component is a pattern and as such has a lot of markup involved for even the very simple usecases. Having a Vue component with `slot`s takes a huge load off the developer to focus on the main content. 

References:
- creativecommons/vocabulary#145
- [Header @ Figma](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=179%3A0)

**Comment by Bob160** [comment]
@dhruvkb can I get to work on this?

Thanks

**Comment by jahnvigupta** [comment]
@Bob160 are you finding some trouble solving this issue? Do you need help or don't want to continue?

**Comment by Bob160** [comment]
@jahnvigupta, I would appreciate your help. Thanks

**Comment by Tanuj22** [comment]
@Bob160 Are you working on this? I would like to take up this issue.

**Comment by Bob160** [comment]
@dhruvkb, please, kindly reassign this issue to @jahnvigupta. Thanks

**Comment by Bob160** [comment]
@Tanuj22 as @jahnvigupta had asked earlier, I think it's only fair to ask that it be reassigned to her.
