### ISSUE TITLE
Create the Footer component

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#196]
**Description**
With the `Footer` component having been built in Vocabulary with the markup and styling already defined, it's time to get the Vue version of the component.

The Footer component is a pattern and as such has a lot of markup involved for even the very simple usecases. Having a Vue component with `slot`s takes a huge load off the developer to focus on the main content.

References:
- creativecommons/vocabulary#180
- [Footer @ Figma](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=639%3A24)

**Comment by sjs8906** [comment]
@dhruvkb I'd like to work on this please :)

**Comment by dhruvkb** [comment]
@sjs8906 please go ahead. Let me know if you face any issues.

**Comment by hemanth-hk** [comment]
Hey @sjs8906, are you still working on this?

**Comment by dhruvkb** [comment]
@hemanth-hk I don't think they are. You go ahead with it.

**Comment by hemanth-hk** [comment]
Before I execute I wanted to know if my "plan" is correct
Basically there is a `Footer.vue` in the `patterns/Footer` dir which I will write according to the references
provided and then bring in into the storybook to kind of isolate and test it... and that should be it, right?

**Comment by dhruvkb** [comment]
Yes @hemanth-hk, that's pretty much it.

**Comment by hemanth-hk** [comment]
I was trying to write the footer component and noticed that the styles were not applying to the footer, So I went into the `node_modules` and found that classes like main-footer, etc are not present, so I looked into the `package.json` to see the version of vocabulary and it was `^1.0.0-beta.2` which is a deprecated version 

---

## Screenshots
### CSS and node_modules
![vocab-footer](https://user-images.githubusercontent.com/43946715/79222792-ccc5a600-7e75-11ea-8394-136fd89dc326.png)
### package.json
![vocab-package](https://user-images.githubusercontent.com/43946715/79223172-76a53280-7e76-11ea-8349-bcdcefddd232.png)
---

This needs to be changed right?

**Comment by dhruvkb** [comment]
Yes @hemanth-hk, you should install the latest version.

**Comment by hemanth-hk** [comment]
So should I create an issue or include this in the `PR` that I'll send for this issue? @dhruvkb

**Comment by dhruvkb** [comment]
@hemanth-hk since it's important to the resolution of the issue so no need to create a separate issue and PR, do it here itself.

**Comment by hemanth-hk** [comment]
@dhruvkb  I opened a draft pull request, please check if I am in the right direction
also, I have some questions regarding this: 
 - Which class will give me the cc logomark, I tried many classes but didn't get, so I just pasted the SVG for the time being?
 - To meet the design I had to change a little bit of the structure of the columns, is it ok?
 - Where should I place the slots or how will I know the spots to place the slots, presently I placed 1 in the draft to make sure it is working

**Comment by dhruvkb** [comment]
@hemanth-hk  you can use the CC logomark by taking the asset from Vocabulary.
```js
import svg from `@creativecommons/vocabulary/assets/logos/cc/logomark.svg`
```

We're not allowed to change the design. But if the footer CSS is not compliant with the design, open an issue in Vocabulary and fix it there. We cannot patch over Vocabulary in this repo.

@panchovm can elaborate on which parts of the footer should be customisable on a site-to-site basis and which are fixed. Whichever parts are customisable should use slots.

**Comment by panchovm** [comment]
The part that can change depending on the site is **the set of links** above the newsletter subscription. All the remained parts are equal in every site.

**Comment by zackkrida** [comment]
@Aakash2408 we're going to close this issue while we revisit some aspects of `vue-vocabulary`. Thank you for your interest!
