### ISSUE TITLE
Create the Tab component

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#197]
**Description**
With the `Tab` component having been built in Vocabulary with the markup and styling already defined, it's time to get the Vue version of the component.

The Tab component is a layout and as such has a lot of markup involved for even the very simple usecases. Having a Vue component with `slot`s takes a huge load off the developer to focus on the main content.

As a hint, Tab would make use of the `SlotRenderer` util that already exists in Vue Vocabulary and was extensively used in the initial versions of the components `TabPane` and `Tabbed`.

References:
- creativecommons/vocabulary#178
- [Tab @ Figma](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=933%3A0)

**Comment by jahnvigupta** [comment]
@dhruvkb I want to take this.
