### ISSUE TITLE
Add usage and contribution guidelines

### ISSUE THREAD

**Issue by megha070** [creativecommons/vue-vocabulary#199]
**Description**
So as to help newbies get started with creative commons and Vue vocabulary a need of one such guide is mandatory.

**Problems solved**
This is to be done for consistency and, more importantly, because it enables us to have documentation on the landing page.

**Alternatives**

**Additional context**

**Want to take up?**

[Yes|No]
yes

**Comment by dhruvkb** [comment]
This is a duplicate of #167.

**Comment by dhruvkb** [comment]
d
