### ISSUE TITLE
update vocabulary logo in the readme file

### ISSUE THREAD

**Issue by Dishebh** [creativecommons/vue-vocabulary#220]
**Description**

Replace old vocabulary logo with the new one in the readme file.

**Want to take up?**

[Yes]

**Comment by Dishebh** [comment]
@dhruvkb please let me know if I can work on it. Thanks!

**Comment by dhruvkb** [comment]
Yes please. You can see creativecommons/vocabulary#416 and creativecommons/vocabulary#419 for reference.

**Comment by Dishebh** [comment]
Opened a PR for the issue.
