### ISSUE TITLE
Adding a "A background display" to the "Change size of preview feature"

### ISSUE THREAD

**Issue by nimishbongale** [creativecommons/vue-vocabulary#225]
**Description**
The preview feature is great, and works like a charm. I do think, however, there is a tiny scope of improvement! I've worked hard in the past on making websites responsive, and I believe it helps reach a bigger audience fairly quickly. 

I would suggest adding a phone-esque background to the preview mode. Something like this:-
 
![load](https://user-images.githubusercontent.com/43414361/83338404-abaffc00-a2e1-11ea-87e4-d8305cf3901c.PNG)

**Problems solved**
From a developers perspective, It is important to be able to judge dimensions and make things look good on all devices. And what better way to be able to visualise it when you can have a mock phone and screen to be able to look at? 

**Alternatives**
If getting these backgrounds proves to be difficult, we could start off with a dummy phone background, which applies to all the cases, and slowly diversifies.

**Additional context**
This is how it looks as of now:-

![send](https://user-images.githubusercontent.com/43414361/83338448-21b46300-a2e2-11ea-9efa-981764fefe87.PNG)

**Want to take up?**
Yes.

**Comment by dhruvkb** [comment]
As long as we're not bloating the repository with phone body images, it seems like a good idea. Looking forward to a working implementation.

**Comment by nimishbongale** [comment]
Thank you @dhruvkb!
I don't think it'll bloat the repo as such. 
Looking forward to working on it!

**Comment by dhruvkb** [comment]
Just a few pro-tips:
- use SVGs (or make it using pure CSS if you want a challenge); they tend to have much smaller file size and much better scalability
- use generalised shapes (per device category and not per individual screen size); most phones and tablets are just glass sandwiches anyways

**Comment by nimishbongale** [comment]
@dhruvkb Yes, I was thinking about using SVG's!

Right, will take that into account. 

Thank you!

**Comment by nimishbongale** [comment]
@dhruvkb 

Does this look fine? 

![embed](https://user-images.githubusercontent.com/43414361/83359869-c2fef000-a39a-11ea-9fdd-fbb0f913ba93.PNG)

Its the actual "tab" component showing within the svg frame.
