### ISSUE TITLE
Create locale component

### ISSUE THREAD

**Issue by ayamba-coder** [creativecommons/vue-vocabulary#226]
**Description**
With the Locale component having been built in Vocabulary with the markup and styling already defined, it's time to get the Vue version of the component.

The locale component is a pattern and as such has a lot of markup involved for even the very simple usecases. Having a Vue component takes a huge load off the developer.
**Want to take up?**
Yes

**Comment by dhruvkb** [comment]
Although we won't be porting all components over to Vue Vocabulary, `Locale` does seem like it warrants to be ported because it needs to be integrated with [Vue i18n](https://kazupon.github.io/vue-i18n/).

**Comment by ayamba-coder** [comment]
@dhruvkb do i create this component thinking of Vue-i18n library only?, are there no future promises of using a different i18n lib?.Just trying to self isolate this component irrespective of the i18n being used.

**Comment by dhruvkb** [comment]
@ayamba-coder there are actually not many libraries for i18n in Vue. Vue-i18n is by far the largest, most widely used of them. You can make it library-agnostic to some extent by emitting events and I'm okay with that approach as well.

**Comment by kgodey** [comment]
This component is getting redesigned.
