### ISSUE TITLE
Set up Dependabot

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#230]
## Problem description
Keeping packages up to date is hard. 

## Solution description
Configure Dependabot to do this for us [via a configuration file](https://help.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-github-dependabot-version-updates).

## Additional context
- Suggested by @nimishbongale in https://github.com/creativecommons/vue-vocabulary/issues/224#issuecomment-636431029
- New [updates to Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) released by GitHub

**Comment by dhruvkb** [comment]
@nimishbongale you can work on it, I don't think write access is needed to work on this issue. Some issues that do need a maintainer permissions are marked 'CC staff only' (this isn't).

**Comment by dhruvkb** [comment]
In addition to the `dependabot.yml` file, we will need to enable Dependabot-native from Settings. @kgodey please do that for the three repos.

**Comment by nimishbongale** [comment]
> @nimishbongale you can work on it, I don't think write access is needed to work on this issue. Some issues that do need a maintainer permissions are marked 'CC staff only' (this isn't).

Ahh alright! I thought it did.

**Comment by nimishbongale** [comment]
> In addition to the `dependabot.yml` file, we will need to enable Dependabot-native from Settings. @kgodey please do that for the three repos.

@dhruvkb  Yeah this is what I was trying to say. My bad.

**Comment by dhruvkb** [comment]
@nimishbongale since you've been focusing your attention here, I think you might not be aware that Vocabulary is our main repo and the center of attention (for now). So if you could sync the improvements (including #227) there too, that would be awesome.

**Comment by nimishbongale** [comment]
> @nimishbongale since you've been focusing your attention here, I think you might not be aware that Vocabulary is our main repo and the center of attention (for now). So if you could sync the improvements (including #227) there too, that would be awesome.

@dhruvkb yep, on it! I've forked the main vocabulary repo too. Will raise an issue and send an equivalent PR for #227.
