### ISSUE TITLE
Update docker structure to match vocabulary repo

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/vue-vocabulary#237]
See implementation in: https://github.com/creativecommons/vocabulary with `/docker` directory and `run.sh` scripts.

**Edit:** Make sure we update the [dependabot config](https://github.com/creativecommons/vue-vocabulary/blob/master/.github/dependabot.yml#L8-L11) when we do this.

**Comment by dhruvkb** [comment]
I really like the `docker/` structure of Vocabulary and any attempt to replicate the behaviour in other repos has my total appreciation 👍.
