### ISSUE TITLE
Unify control dimensions

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#24]
Currently controls have been independently styled and are therefore very disparate in terms of their dimensions. So placing these components adjacent to each other leads to a bad look. The goal is to ensure that components have consistent dimensions, mainly heights but also, if possible, widths.

**Comment by MysticNas** [comment]
Hey ! I d like to work on this one. Hopefully it could be my first contribution as an outreachy applicant?

**Comment by MysticNas** [comment]
hey dhruvkb ! I haven t heard from you yet; can I PR it?  thank you

**Comment by MysticNas** [comment]
@dhruvkb? ...

**Comment by kgodey** [comment]
I believe @dhruvkb is traveling. @hugosolar maybe you could weigh in?

**Comment by MysticNas** [comment]
Thanks for replying to me. If @hugosolar could lead me into this issue , that d be great. 

Thanks again @kgodey

**Comment by dhruvkb** [comment]
@MysticNas sorry for not replying for so long, you're welcome to work on this. In fact, as a general rule of FOSS, unless someone is already working on an issue and your work would override theirs, you're always invited to contribute.

**Comment by MysticNas** [comment]
hello @dhruvkb , would it possible for you to screenshoot one of the said unconsistent controls. I m not sure which ones I should work on. Thank you.

**Comment by dhruvkb** [comment]
@MysticNas the following is a table of controls and their dimensions.

| Component | Height | Border |
|-|-|-|
| Button | 35.2 | 1 |
| InputField | 35.2 | 1 | 
| SelectField | 37.2 | 1 |
| SwitchField | 20 | 4 |
| ChoiceField | 24 | 1 |

Ideally these components should coalesced to a `2.25em`/`2.5em` height scale and set to a box-sizing of `border-box` so that the border is factored into the height. Some fields such as the switch and choice are smaller by design, so they should use margins for alignment (or be made bigger if that looks better). They should ideally have a `control.styl` stylesheet to inherit from so that all the values are consistent across the system.

The goal here is to unify all these control heights and borders so that
- if they happen to be inlined, all their upper and lower edges are aligned
- if they happen to be stacked, all their start edges (left if LTR and right if RTL) are aligned

Hope that clarifies it!

**Comment by MysticNas** [comment]
![screenshot mission](https://user-images.githubusercontent.com/54336075/66791647-192e2a00-eec3-11e9-8493-8eea6c14f9b4.jpg)
 Thank it helped.    From what I understand , the boxes I have circled in red are what you call "controls". However , I couldn't find the heights and Border measurements you mention (35.2/ 1). Could you tell me which file you saw those measurements so I know which file I should work on?  Also, It appears I should learn Vue in order to use a  "control.styl" stylesheet. I ll try my best to fiddle with this framework.

**Comment by dhruvkb** [comment]
@MysticNas a control is any component that is meant to provide input to the app (such as a button or input field or switch) as opposed to a presentational component that merely shows content (such as an image view or heading). The red boxes you drew are just previews for the component allowing you to see how it looks and works in actual use.

Those measurements were taken using the box layout visualiser available in your browser’s dev tools. Try <kbd>F12</kbd>.

Some familiarity with Vue is essential because Vocabulary is completely built upon the framework.

**Comment by dhruvkb** [comment]
With PRs #52 and #53, both `SwitchField` and `Shield` have been converted to a `36px`/`2.25em` height. This value should therefore be taken as the de facto standard for the other controls.

**Comment by dhruvkb** [comment]
This issue that has, unfortunately, been rendered irrelevant with the usage of Bulma as the base for Vocabulary. Closing.
