### ISSUE TITLE
Install Netlify as a GitHub application

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#39]
Currently GitHub Pages are being used to serve the Vocabulary website. This comes with its own set of shortcomings, the main one being the need for manual builds into the `docs/` directory each time documentation is updated in the source code.

Having Netlify installed would allow us to set up an auotmatically deployed, always up to date version of Vocabulary documentation served independently from the codebase.

**Comment by HAMZABoxer98** [comment]
I deployed the style guide with Netlify in #37. what additions needed here ?

**Comment by dhruvkb** [comment]
@HAMZABoxer98 to setup CD, Netlify GH app, needs to have access to the repo, something that only organisation management has permissions to do. Neither you nor I can set this up, so I asked @kgodey ma’am to set this up.

**Comment by HAMZABoxer98** [comment]
@kgodey , just follow these steps: 
https://youtu.be/mN9oI98As_4?list=PLzlG0L9jlhEPMR8haUPkxj2hJ_3jh5qa6
at 1:57 , fill it like that:
![Capture](https://user-images.githubusercontent.com/12598426/66700252-c69c1480-ecee-11e9-8f84-c312372a792e.PNG)
Finally, when you visite that link you will see a blank page because `index.html` is not working and I don't know why, so you have to browse manually into `/styleguide` or `/storybook`.

**Comment by dhruvkb** [comment]
`index.html` for the root directory does not work because of the public directory being set [here](https://github.com/creativecommons/cc-vocabulary/blob/64148c8948ff84f7d7eed4654a838280f5db4e4e/vue.config.js#L2).

**Comment by kgodey** [comment]
I set it up and it's being deployed here: https://cc-vocabulary.netlify.com/ but something appears to be wrong since the page is showing up as blank for me.

I sent Netlify an email about switching to their Open Source Plan and I'm going to keep this issue open until that's resolved as well.

**Comment by dhruvkb** [comment]
@kgodey the issue is that the Vocabulary website was configured to load on a subdirectory (as is the case with GH pages). See [comment](https://github.com/creativecommons/cc-vocabulary/issues/39#issuecomment-541318582).

**Comment by dhruvkb** [comment]
Some changes might be required for this to work on Netlify, more specifically using env vars to configure the Vue build process.

**Comment by kgodey** [comment]
Okay, let me know what you need me to do.

**Comment by dhruvkb** [comment]
@kgodey you don’t need to do anything in particular afaik. It’ll work out on its own.

**Comment by dhruvkb** [comment]
https://github.com/creativecommons/cc-vocabulary/issues/39#issuecomment-542054853 has been addressed in cea80ed. The homepage of Vocabulary is now loading as expected.

**Comment by dhruvkb** [comment]
Tracking this on Asana.
