### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#4]
Currently only one or two components have test coverage. This is abysmal, but hopefully understandable given the time-constrained nature of the Summer of Code program under which the library was developed.

This inadequate test coverage has prevented new features from being developed freely because of the looming fear of unknowingly breaking functionality somewhere down the line. The solution is to write tests for all components (from elements to templates).

This is a good way to get familiar with the codebase and get an in-depth introduction to the components. Completing this will also enable us to set up continuous deployment of the library to `npm` and of the styleguide to GitHub Pages.

**Comment by HAMZABoxer98** [comment]
Hi @dhruvkb 😄 , I am from Outreachy and I want to practice more on Testing... currently I am working on CC license chooser, can I work on this one too ?
I am new to the testing world, so it would be a pleasure for me if I send you a PR after each component, so you can review my test ^_^.
I have a free time, so I can provide a full test coverage.

**Comment by dhruvkb** [comment]
Sure @HAMZABoxer98 one PR per component sounds well. Make sure every component is tested for these aspects:

- [ ] Existence of DOM elements (Whether the component renders the correct HTML tag)
- [ ] DOM action events (Whether clicking or typing raises the apt `@click` or `@input` event)
- [ ] Accessing Vue wrapper properties (Whether data and computed properties are calculated correctly)
- [ ] Mocking methods and modules (Whether the component behaves properly)
- [ ] Internationalisation (Whether the component supports i18n with Vue i18n)

**Comment by dhruvkb** [comment]
Also adding the need to test code style with `lint` and also test code accessibility with suitable tooling as suggested in #13.

**Comment by HAMZABoxer98** [comment]
Hi @dhruvkb , what I need to do here ?

**Comment by dhruvkb** [comment]
Adding the need to incorporate E2E testing using Selenium _or other competent tooling_ into the library, thus increasing the scope and duration of the task and increasing its relevance above and beyond a good first issue to introduce new developers to the library.

**Comment by bax-uva** [comment]
Hi @dhruvkb, I'm an Outreachy applicant, can I be assigned to this issue as well?

**Comment by dhruvkb** [comment]
Sorry for this random assign and unassign events. That’s my GitHub client messing up.

**Comment by AmanR28** [comment]
Can I also help in writing some tests?

**Comment by dhruvkb** [comment]
@AmanR28 we are currently revamping the architecture of Vue Vocabulary. Your contributions to [creativecommons/vocabulary](https://github.com/creativecommons/vocabulary) will be more impactful in the long term.

**Comment by kgodey** [comment]
Closing this for now, we may reopen once we have more components.
