### ISSUE TITLE
Set up continuous deployment

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#5]
Currently Vocabulary is being manually pushed to `npm`. This can be automated with CircleCI so that it can automatically build and publish the package once all tests pass successfully.

Best way to do this is to use some mechanism on Github Actions to detect when a new *tag* is pushed and trigger the run the [deploy script](https://github.com/creativecommons/vocabulary/blob/master/deploy.sh). It can't be the release name. It has to be able to detect a new tag, because the tag name matches the version on package.json.

**Comment by dhruvkb** [comment]
Add 'Setting up [GitHub Actions](https://github.com/features/actions)' to the list of things to do under this issue.

**Comment by xumisyou** [comment]
no

**Comment by dhruvkb** [comment]
Also adding the need to test code style with `lint` and also test code accessibility with suitable tooling as suggested in #13.

**Comment by dhruvkb** [comment]
Continuous deployment to Netlify has been achieved with cea80ed.

**Comment by dhruvkb** [comment]
Closed accidentally. Continuous/automatic deployment to `npm` and GitHub Pages remains to be achieved.

**Comment by bax-uva** [comment]
Hi @dhruvkb, I would like to work on this issue, but to do it I have to wait until issue#4 is complete?

**Comment by dhruvkb** [comment]
@bax-uva, this is a very long-term issue which we're hoping to tackle under Outreachy itself because the contribution period is insufficient to complete it. You could actually help contribute to #4 instead.

**Comment by Dhruvi16** [comment]
Hey! I found this article for automated npm publishing - [Article](https://medium.com/techmindtickle/continuous-deployment-for-publishing-packages-4e5ef327ea37)

I read about semantic_release and it looks great - [Check it out](https://github.com/semantic-release/semantic-release)

**Comment by dhruvkb** [comment]
References creativecommons/vocabulary#121.

**Comment by dhruvkb** [comment]
Waiting for GitHub Actions to replace CircleCI #205 and then we can use GitHub Actions 
```
on: release
```
to automatically push new versions to npm whenever a new release is tagged on GitHub.

**Comment by SaurabhAgarwala** [comment]
@dhruvkb Can I work on this now?
