### ISSUE TITLE
Customize Styleguide footer

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#54]
The footer currently shown on the styleguide says
> "Generated with Vue Styleguidist"

which isn't helpful at all. A better footer is needed which is more informative.

I particularly like the footer of the [Carbon design system](https://www.carbondesignsystem.com/).
![image](https://user-images.githubusercontent.com/16580576/67142927-d46c0f80-f283-11e9-9398-ddab263b5b3b.png)

Our own `Footer` component is pretty cool too.

This would also resolve #43.

**Comment by sudoshweta** [comment]
Hi, Can I work on this issue?

**Comment by dhruvkb** [comment]
Sure, take it up

**Comment by sudoshweta** [comment]
Hi, does this footer needs to be implemented on each page? I saw the elements, "Generated with Vue Styleguidist" is there on almost every page. 
![footer](https://user-images.githubusercontent.com/21018589/67157690-2af15080-f34d-11e9-8ca6-21af81e4ac02.png)

**Comment by dhruvkb** [comment]
Yeah, the idea is to replace the "Generated with Vue Styleguidist" with our footer.

**Comment by dhruvkb** [comment]
This plan has been dropped in favour of #6, which eliminates Vue Styleguidist entirely.
