### ISSUE TITLE
Add missing features to Popup

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#57]
**Description**
The newly developed component `Popup` is a wrapper on `Section` and therefore lacks the traditional pointing arrow associated with components of this nature.

**Problems solved**
A popup with an arrow clearly points to the component that the popup is for. This is especially useful if the popup spans multiple lines vertically or multiple words horizontally.

**Alternatives**
Popups without arrows look and work fine which is why the option must be opt-in using a `Boolean` prop.

**Comment by sargamm** [comment]
Hi @dhruvkb , I would like to work on this

**Comment by sargamm** [comment]
Before I can start, can you guide me a little?

**Comment by dhruvkb** [comment]
@sargamm, you're welcome to work on this.

**Comment by dhruvkb** [comment]
@sargamm I'd be happy to help on Slack if you need help getting started or have queries that need to be resolved.

**Comment by sargamm** [comment]
I don't know how to use slack. how do i go about with it?

**Comment by dhruvkb** [comment]
@sargamm [this page](https://opensource.creativecommons.org/community/) points to resources and instructions.

**Comment by dhruvkb** [comment]
Adding the request for a feature to delay the appearance of the popup. Ideal implementation would be the ability to select from the predefined tokens or specify custom delay in miliseconds.

**Comment by vksonagara** [comment]
I would like to work on this issue.
