### ISSUE TITLE
Set up a component playground experience

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#6]
A long text file is a poor way to show all variants of a component. Especially given that all these variants can also be applied simultaneously in any permutation.

An interactive playground where toggles can be turned on/off and variants can be chosen from a list of checkboxes would make it easy to mix and match and overlay variations.

This is offered to some extent by [Storybook](https://storybook.js.org/), but integrating it with [Styleguidist](https://vue-styleguidist.github.io/) is not straightforward. Also I'm inclined towards presenting this interface within the style guide rather than another completely different ecosystem. Storybook has a documentation system coming up so that might bridge the gap or replace Styleguidist entirely.

Anyway Storybook does have some features that Styleguidist lacks (you have to type out code snippets to see them in action, no UI or knobs) so initiating it is nevertheless a step towards the positive direction.

**Comment by dhruvkb** [comment]
A part of this interface can be an interactive color and shade experience, that allows the user to select colors and shades using `SelectField`s and toggle inverted mode using a `SwitchField`.

Something along these lines has been implemented in [the documentation for the `Header`](https://opensource.creativecommons.org/cc-vocabulary/#!/Header).

**Comment by dhruvkb** [comment]
As Storybook comes closer and closer to providing the features afforded by Styleguidist, and then more of its own, it has been added to the project as of d3b8612 and can be seen at [this link](https://creativecommons.github.io/cc-vocabulary/storybook). Work remains on adding components to this Storybook and documenting their common and edge cases.

**Comment by dhruvkb** [comment]
Storybook 5.2.0 [adds](https://git.io/JenaN) support for :books: DocsPage and :framed_picture: Design System. This is relevant because it means Storybook is officially in Styleguidist territory.

**Comment by ifylala** [comment]
I am Ify an Outreachy Intern, I would like to resolve this issue. kindly assign it to me.

**Comment by dhruvkb** [comment]
@ifylala I should point out that this is a long-term issue and thus you should either break it down into smaller logical parts before getting to coding. Also from the point of view of your Outreachy application and your newness to the codebase, you should check out [`good-first-issue`](https://github.com/creativecommons/cc-vocabulary/labels/good%20first%20issue) to get familiar with the code.

**Comment by dhruvkb** [comment]
@ifylala Any updates on this?

**Comment by ifylala** [comment]
> @ifylala any updates on this?

No update yet @dhruvkb , like you said earlier it's best if it is done in bits. Can you help me in breaking it down? Because I am a bit confused.

**Comment by ifylala** [comment]
> > @ifylala any updates on this?
> 
> No update yet @dhruvkb , like you said earlier it's best if it is done in bits. Can you help me in breaking it down? Because I am a bit confused.

**Comment by dhruvkb** [comment]
@ifylala let’s start with elements, that too the first one which is `<Button/>`. Can you convert the styleguide for Button into an interactive storybook? By interactive I mean like instead of coding in every prop, use “knobs”.

**Comment by ifylala** [comment]
@dhruvkb please explain what you mean by "knobs"

**Comment by dhruvkb** [comment]
Storybooks has been updated to version 5.2, with documentation addon and JSX support. @chidexebere is taking on this issue for week#1 of Outreachy.
