### ISSUE TITLE
Z-index | stacking order system

### ISSUE THREAD

**Issue by rashadmad** [creativecommons/vue-vocabulary#65]
**Description**

Create a stacking system for all of the elements in vocabulary.

**Problems solved**

Where elements like sticky footers or headers have to play nice with each other it can be difficult for teams to know what elements take priority. In many cases you may have elements popping up where they don't belong. exp: buttons being viewed over header elements.

**Alternatives**

Other design systems take advantage of Z-index variables like the morning star design system here 
http://designsystem.morningstar.com/visual-language/layering.html

**Additional context**
<img width="1035" alt="Screen Shot 2019-10-30 at 2 59 41 PM" src="https://user-images.githubusercontent.com/5515036/67896978-74028b00-fb2b-11e9-845e-db46625951b1.png">

**Want to take up?**

[Yes]

**Comment by dhruvkb** [comment]
@rashadmad this is a solid idea, get on it!

**Comment by dhruvkb** [comment]
The feature falls outside our current plan for the project, even more so with the removal of the token system entirely from Vocabulary. Therefore closing.
