### ISSUE TITLE
Flatten DOM as much as possible

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#71]
**Description**
While Vocabulary is a Vue package, not all usages of Vocabulary are or will be. This means that the vanilla CSS distribution of Vocabulary will end up being widely used. This means that the templates that Vue was writing on behalf of the developer will now have to be written by the developers themselves. Some especially complicated ones (such as the footer) are too nested to be written by hand and must be simplified as much as possible.

This essentially means minimising the amount of nesting and the number of classes in use in templates across Vocabulary.

**Problems solved**
Have a flatter DOM structure makes it easy to manually do the work that Vue templates were doing when using Vue. The goal is to simplify the DOM in components as much as possible.

**Comment by Dhruvi16** [comment]
I would like to help here!
Thank you.

**Comment by dhruvkb** [comment]
@Dhruvi16 go ahead.

**Comment by Dhruvi16** [comment]
Hey! I am not clear about the problem. Could you please share some resources?
Thank you!

**Comment by kgodey** [comment]
Unassigned @Dhruvi16 since there hasn't been activity on this issue. Also adding a "not ready for work" label because Vue Vocabulary is undergoing large changes.

**Comment by dhruvkb** [comment]
Since simple elements are not even going to be implemented anymore, this issue doesn't mean much anymore.
