### ISSUE TITLE
Provide documentation for translators to add translations to Vocabulary

### ISSUE THREAD

**Issue by kgodey** [creativecommons/vue-vocabulary#72]
**Description**
Currently, there are no instructions available to translators for how to add new translations to Vocabulary.

**Problems solved**
Lowers barriers for new translations to be added.

**Comment by dhruvkb** [comment]
@kgodey am I correct to assume that this can only be implemented after #73 is resolved?

**Comment by kgodey** [comment]
That depends, if #73 is going to take a while, I'd add instructions under the current system and then update then when #73 is resolved.

**Comment by dhruvkb** [comment]
I’ll just make #73 high priority to avoid translators from wasting their efforts learning a new system that’s going to be deprecated.

**Comment by kgodey** [comment]
I'm going to close this because we're simplifying Vocabulary and may not have translations directly in there.
