### ISSUE TITLE
Integrate Vocabulary with Transifex

### ISSUE THREAD

**Issue by kgodey** [creativecommons/vue-vocabulary#73]
**Description**
CC currently manages translations for our Deed and Chooser pages through Transifex. We'd like to move towards managing all translations through Transifex. We should manage Vocabulary translations there and automatically sync new translations.

**Problems solved**
Consistent translation infrastructure, better access to translators.

**Additional context**
This issue will require design work before coding starts to ensure that we have our Transifex settings set up right.

**Comment by brenoferreira** [comment]
The Vocabulary components are to be reused in multiple websites, and different websites can have different text. What's the reasoning for the translations being in the Vocabulary, and not in the individual sites in which the Vocabulary is used?

**Comment by dhruvkb** [comment]
Translations are largely left out of Vocabulary, excepts in components where the text is a part of the component. For example, consider the select component. So while most components such as `Button`s leave translations out of Vocabulary, others such as `SelectField`s translate the zeroth option namely "Select"/"चुने". Components such as the `Footer` offer translations in the hope that being standardised, the text in them would largely be unmodified in the app using them.

**Comment by brenoferreira** [comment]
I think components like `Select` should have a default text, like "Select", and accept a prop to override that default text, therefore enabling users of the component to localize it accordingly.

**Comment by kgodey** [comment]
I'm going to close this because we're simplifying Vocabulary and may not have translations directly in there.
