### ISSUE TITLE
Change the presentation of colors in tokens

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#81]
The old card view for colors worked out well in the past when each color was present in four shades. With each color now having five shades, it is no longer feasible to use cards to present colors. Plus using separate cards for every shade creates the impression that each of this shade is an independent hue in itself, which is decidedly not the case here.

We need a better way to present information, and I personally think a table would be a good way to move forward.

**Comment by ritesh-pandey** [comment]
Something like this? 
https://www.w3schools.com/colors/colors_names.asp

**Comment by dhruvkb** [comment]
@ritesh-pandey essentially yes, but more _beautiful_?

**Comment by dhruvkb** [comment]
**References:**
- [Atlassian](https://atlassian.design/guidelines/brand/color) for clear separation of brand colours from functional colours
- [Shopify](https://polaris.shopify.com/design/colors#section-color-palette) for choice between hex codes and SCSS

**Comment by kgodey** [comment]
@dhruvkb now that we decided not to do shades of the brand colors, will you update the ticket description?

**Comment by dhruvkb** [comment]
@kgodey yes, we planned not to make shades for brand colours but our functional colour palette (to be designed in conjuction with @panchovm) will still be shaded. So a better way to depict colours will nevertheless be very productive.

**Comment by dhruvkb** [comment]
To add to https://github.com/creativecommons/vue-vocabulary/issues/81#issuecomment-561143360, here is an example of a clean colour presentation in Storybooks. This is Storybook's [own design system](https://storybook-design-system.netlify.com/?path=/docs/design-system-colors--page).

Here's another view of the same page. Beautiful.
![image](https://user-images.githubusercontent.com/16580576/70118191-6cd01f00-168d-11ea-9a29-ee2de3380926.png)

**Comment by panchovm** [comment]
[Atlassian](https://atlassian.design/guidelines/brand/color) does a good job by presenting the primary palette (brand colors in our case) and then introducing the variations. The example above works for visualizing hue, light, and saturation changes, but does not work for how to use them.

**Comment by dhruvkb** [comment]
With Storybook adding [DocBlocks](https://medium.com/storybookjs/storybook-docs-for-new-frameworks-b1f6090ee0ea), we might not have to think about that in too much detail.

**Comment by dhruvkb** [comment]
This is no longer meaningful.
