### ISSUE TITLE
Find and replaces occurrences of vocabulary with vue-vocabulary

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#84]
Vocabulary has now been split into two repositories:
- style-only library named [`vocabulary`](https://github.com/creativecommons/vocabulary)
- Vue component library named [`vue-vocabulary`](https://github.com/creativecommons/vue-vocabulary)

This split has left us with rampant misnaming throughout the project, in the HTML titles, in copy texts, in documentations and in links. These mistakes must be resolved going forward. That is the goal of this issue.

**Comment by ritesh-pandey** [comment]
@dhruvkb Can I take this up?

**Comment by dhruvkb** [comment]
@ritesh-pandey yes, please go ahead.

**Comment by ritesh-pandey** [comment]
Next I am picking up `src` directory

**Comment by ritesh-pandey** [comment]
There is one more [file](https://github.com/creativecommons/vue-vocabulary/tree/master/documentation/metafiles) where we should use `Vocabulary` instead of `CC Vocabulary`. But I am not sure. @dhruvkb can you help?

**Comment by dhruvkb** [comment]
Where exactly in the [file](https://github.com/creativecommons/vue-vocabulary/tree/master/documentation/metafiles)?

**Comment by ritesh-pandey** [comment]
> Where exactly in the [file](https://github.com/creativecommons/vue-vocabulary/tree/master/documentation/metafiles)?

First paragraph. First line.
```
As CC Vocabulary grows, so does the effort for maintaining code quality and keeping technical debt to a minimum. Having a set of rules makes sure that some semblance of order is maintained in the chaos that is developing and maintaining a component library.
```

**Comment by dhruvkb** [comment]
Yeah it should be Vocabulary.

**Comment by dhruvkb** [comment]
@ritesh-pandey are there any more occurrences of CC Vocabulary in the repository? Or any mislabeled occurrences of Vocabulary?

**Comment by ritesh-pandey** [comment]
You read my mind. I was writing the same comment. 

I am unable to find any more such occurrences.

**Comment by dhruvkb** [comment]
Great, feel free to take up another issue. Closing.
