### ISSUE TITLE
Vocabulary CDN for styles not found

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/vue-vocabulary#89]
**Description**
The CC Search browser Extension uses the following cdn for vocabulary styles https://unpkg.com/@creativecommons/vocabulary@0.0.0-alpha.24/css/vocabulary.css

It is not working and thus the styles in the production version of the extension are not rendering. This is a problem because even if we change the CDN link with an updated one and push a new version of the extension to the store, it will take more than a week to pass the evaluation process of the various browser extension stores  

**Reproduction**
- Open the options page of the CC Search extension.

**Expected behavior**
The full options page must be rendered with Vocabulary styles.

**Screenshots**
![Screenshot from 2019-12-05 21-16-13 (1)](https://user-images.githubusercontent.com/34679965/70250913-a6e01480-17a4-11ea-86c6-c0f12ba3b67d.png)

**Comment by makkoncept** [comment]
@dhruvkb a gentle ping...

**Comment by dhruvkb** [comment]
@makkoncept sorry for not noticing early. To account for the repo split, please update the URL to https://unpkg.com/@creativecommons/vocabulary.

**Comment by makkoncept** [comment]
@dhruvkb I understand, but can there be some temporary solution right now because as I mentioned that it will take at least 1 week before the chrome and firefox browser extension store verifies and pushes the new update.

**Comment by dhruvkb** [comment]
Yes, I am out right now, but you should see it working in a few hours. I'll get home and immediately push a temporary update to the package. Meanwhile do update the URL and submit it for verification, approval and push.

**Comment by makkoncept** [comment]
Okay, thanks!

**Comment by dhruvkb** [comment]
Pushed an update and @kgodey tells me that it is working now. In the meantime, however, you should change the URL as soon as possible. I'd recommend you set it to https://unpkg.com/@creativecommons/vocabulary@0.0.0-alpha.22/css/vocabulary.css as that is the last release before backwards-incompatible, breaking changes were made to the repositories.
