### ISSUE TITLE
Integrate emoji with the library

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#9]
Emoji can only improve an app or library. There is currently no emoji support leading to inconsistent output across browsers. 

The simplest example is this different output.

Browser | Font | Character | Rendered
-|-|-|-
Chrome | Noto Emoji | US flag | Yes
Chrome | Noto Emoji | IN flag | No
Chrome | Noto Emoji | BR flag | No
Firefox | Twemoji | US flag | Yes
Firefox | Twemoji | IN flag | Yes
Firefox | Twemoji | BR flag | Yes

This inconsistency in the output (interestingly, even within the browser) is a major frustration. Clearly, leaving the rendering to the browsers' default is not ideal. An alternative is to agree upon an emoji font, deploy it across browsers and operating systems.

Here are some resources to get started:
- [Twemoji](https://github.com/twitter/twemoji)
- [Twemoji Awesome](https://github.com/ellekasai/twemoji-awesome)

The goal is to integrate Twemoji (or another competent emoji library) into the project.

**Comment by SamOdum** [comment]
Hello @dhruvkb , I am an Outreachy applicant and I would love to work on this issue. But first, I would love to talk to you about it. Is that OK?

**Comment by MysticNas** [comment]
Hey, @dhruvkb, id like to give it a go ! is it ok?

thanks

**Comment by dhruvkb** [comment]
@SamOdum feel free to talk here or on Slack. @MysticNas I have already assigned #24 to you.

**Comment by dhruvkb** [comment]
@SamOdum any updates?

**Comment by SomtochiAma** [comment]
I would like to work on this issue, How can I get started. The Twemoji-awesome is no longer maintained but it seems like it can still be used.

**Comment by dhruvkb** [comment]
@SomtochiAma if Twemoji Awesome is deprecated, you should use [Twemoji](https://github.com/twitter/twemoji) directly. Emoji Awesome has not been updated in a very long time, which would be a problem as the world of emoji is very fast-paced (new ones are added very frequently).

**Comment by brenoferreira** [comment]
Are we going to be using Emoji so extensively to require use of Twemoji? What do you think about we using native emojis for now and if we realise later that we're having issues that Twemoji might fix, we can adopt it later

**Comment by dhruvkb** [comment]
I agree with @brenoferreira that we can always add the component again if required. Mainly flags will be the main issue without Twemoji as they are generally rendered using emoji ligatures which is a relatively new and not widely adopted technology.

**Comment by kgodey** [comment]
I'm still not clear how this would be used in practice for emojis. Would emojis automatically be detected and rendered correctly? How would that work in core Vocabulary? @dhruvkb

**Comment by dhruvkb** [comment]
The current implementation of the `Emoji` component replaces emoji codepoints with the appropriate SVG or PNG files. Although this leads to consistency in presentation and is actually recommended by Twemoji itself, replacing text with images is not optimal.

To avoid having to scan the entire DOM for emoji, we came up with the `Emoji` component and tag which always parses its contents using the Twemoji parser.

A better implementation would just use a more compliant font wherever an emoji was to be rendered by setting the CSS `font-family` property. As CSS is involved, that code would reside in the Vocabulary project.

**Comment by dhruvkb** [comment]
@kgodey finally what are we doing about Emoji? Do we parse them and render SVGs for consistency or do we allow the OS to handle it without our interference?

**Comment by kgodey** [comment]
Closing this, see my comment here: https://github.com/creativecommons/vocabulary/issues/102
