### ISSUE TITLE
Restyle buttons

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/vue-vocabulary#92]
Restyle buttons according to this design document https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Vocabulary.-Design-Library?node-id=0%3A222

**Comment by Dhruvi16** [comment]
I would love to take this up!
Thank you.
Dhruvi

**Comment by dhruvkb** [comment]
@brenoferreira with creativecommons/vue-vocabulary#95, these buttons can now be created with the code snippets as shown.

```html
<Button roundness="slight" brand="orange" size="huge">BUTTON</Button>
```
![Big](https://user-images.githubusercontent.com/16580576/71779329-eedc9c00-2fdb-11ea-975c-4e8690e9b3ec.png)
```html
<Button :tone="5" roundness="slight" simplicity="slight" size="huge">BUTTON</Button>
```
![BigBorder](https://user-images.githubusercontent.com/16580576/71779332-f8660400-2fdb-11ea-8448-27a423dab26f.png)
```html
<Button brand="forest" roundness="slight">BUTTON</Button>
```
![Small](https://user-images.githubusercontent.com/16580576/71779334-fb60f480-2fdb-11ea-8306-a619f7924e76.png)
```html
<Button simplicity="slight" roundness="complete" :tone="2">Label</Button>
```
![Tag](https://user-images.githubusercontent.com/16580576/71779408-732f1f00-2fdc-11ea-97f9-a0215f782abb.png)
