### ISSUE TITLE
Restyle form input fields

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/vue-vocabulary#93]
Restyle form input fields according to this design document https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Vocabulary.-Design-Library?node-id=0%3A250

This will include restyling `input[type=text]`, `select` and removing the styles for `input[type=checkbox]` `input[type=radio]`, as these will have default OS styles

**Comment by dhruvkb** [comment]
I do think that checkboxes and radios will need some styling, no matter how simplistic, for consistency. Without them, they will end up appearing wildly different on different browsers and different operating systems, ranging from boxy ones on Windows to rounded on Mac OS.

**Comment by brenoferreira** [comment]
That's fine. It's even better because it gives people a look they are more used to in their own environment.

**Comment by brenoferreira** [comment]
@panchovm Can you confirm that this checkbox/radio button thing is correct?

**Comment by panchovm** [comment]
The style for basic components like checkboxes and radios should be simple. We will achieve the design consistency and look and feel through more complex areas and sections like header, CTAs, and so on.
