### ISSUE TITLE
Define reasonable viewports

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/vue-vocabulary#96]
**Description**
Although added to Storybook, the addon for viewports has not been configured and therefore only presents limited viewport options that are not the most illustrative of the features offered by Vocabulary.

**Expected behavior**
The addon should offer a richer selection of screen sizes and devices.

**Additional context**
The documentation for the addon describes the steps to define a new viewport: https://www.npmjs.com/package/@storybook/addon-viewport

**Comment by Dhruvi16** [comment]
Hey! I can take this up.
Thank you!
Dhruvi

**Comment by dhruvkb** [comment]
@Dhruvi16 please go ahead.

**Comment by Dhruvi16** [comment]
Hey! I have a doubt about configuration. I am not sure if I need to configure the addon globally or per component and how does it make a difference? 
Thank you
Dhruvi

**Comment by dhruvkb** [comment]
The addon should be configured globally as all components need to satisfy our responsiveness criteria.
